### ISSUE TITLE
UnidentifiedImageError: cannot identify image file '/tmp/working_directory/tmpx7zwz0px/RT_ICON_GROUP_0_ICON_0.ico'

### ISSUE THREAD

**Issue by sSharonV** [CybercentreCanada/assemblyline-service-pefile#18]
Hey,
I'm a tech guy that helps our IR team to upgrade their Infra' for improving their capabilities with AL4.
They are still using AL3 and are craving to make the upgrade stable as possible.

After I've done the setup and tried to scan some sample files I notice that there is an error that occurs for some awkward causes.

The service PEfile (4.1.0.stable5) keep crashing for the following tray:

> File "/var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline_v4_service/common/base.py", line 133, in handle_task
>     self.execute(request)
>   File "/opt/al_service/pe_file/pe_file.py", line 710, in execute
>     self.get_pe_info(G_LCID)
>   File "/opt/al_service/pe_file/pe_file.py", line 333, in get_pe_info
>     image_section.add_image(path, name, 'Extracted RT_ICON')
>   File "/var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline_v4_service/common/result.py", line 320, in add_image
>     res = self.request.add_image(path, name, description, classification)
>   File "/var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline_v4_service/common/request.py", line 67, in add_image
>     img = Image.open(path)
>   File "/var/lib/assemblyline/.local/lib/python3.9/site-packages/PIL/Image.py", line 3030, in open
>     raise UnidentifiedImageError(
> **UnidentifiedImageError: cannot identify image file '/tmp/working_directory/tmpx7zwz0px/RT_ICON_GROUP_0_ICON_0.ico'**

I've asked for help on the discord channel associated with AL4 - but no answers came from there :)
I would like to know if there could be a work-around to this issue.

Thanks for your contribution :)

**Comment by cccs-kevin** [comment]
Closed by PR https://github.com/CybercentreCanada/assemblyline-service-pefile/pull/19

**Comment by sSharonV** [comment]
thanks for the fix!
it's working on 4.1.0.stable6
